
server:
  servlet:
    context-path: /card-service

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:///dev-db
    username: admin
    password: Dace2831!
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: run-sql-spring:asia-northeast1:card-db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
